"""add otp and otp_time to user table

Revision ID: b81d035f9f39
Revises: 628521de19e6
Create Date: 2025-12-04 18:05:20.200371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81d035f9f39'
down_revision: Union[str, Sequence[str], None] = '628521de19e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_time')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
